name: Rust

on:
  push:
    branches: [ staging, trying, master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: Swatinem/rust-cache@v1
      #- name: cache
      #  id: cache-target
      #  uses: actions/cache@v2
      #  with:
      #    path: target
      #    key: dfasdfgasdf-${{ runner.os }}
      - name: Check
        run: |
          cd xtask
          cargo xtask ci

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check fmt
        run: find -name '*.rs' | xargs rustfmt --check  --skip-children --unstable-features --edition 2018

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cd embassy && cargo test

  metapac_gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Generate pregenerated metapac
        run: cd stm32-metapac-gen; cargo run --release
